version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Standard Redis port

  aggregation_service:
    build:
      context: .  # Set the build context to the aggregation_service directory
      dockerfile: Dockerfile  # Use the Dockerfile in this directory
    volumes:
      - ./app:/app  # Mount the entire app directory correctly into /app
      - ./requirements.txt:/app/requirements.txt  # Mount requirements file for easy update
    ports:
      - "8100:8100"  # Application port for external access
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1  # Ensures that Python output is not buffered (useful for logging)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8100"]
