version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Standard Redis port

  aggregation_service:
    build:
      context: .  # Set the build context to the aggregation_service directory
      dockerfile: Dockerfile  # Use the Dockerfile in this directory
    volumes:
      - ./app:/app  # Mount the app directory into /app for consistency
      - ./requirements.txt:/app/requirements.txt  # Mount the requirements file
    ports:
      - "8100:8100"  # Application port
      - "5680:5678"  # Debugger port for debugging via IDE
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1  # Ensures Python output is not buffered for real-time viewing
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8100", "--reload"]
